driver:
  name: vagrant

provisioner:
  name: chef_zero
  nodes_path: test/fixtures/nodes
  clients_path: test/fixtures/clients
  environments_path: test/fixtures/environments
  data_bags_path: test/fixtures/data_bags
  client_rb:
    environment: test

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[chef-vault]
      - recipe[test]
  - name: secret_resource
    run_list:
      - recipe[chef-vault]
      - recipe[test::chef_vault_secret]
  - name: with-sugar
    run_list:
      - recipe[chef-sugar]
      - recipe[chef-vault]
